name: JukeAlert
main: com.untamedears.JukeAlert.JukeAlert
version: 1.2.1
depend: [Citadel]
commands:
  ja:
    description: Describes plugin
    usage: /ja
  jahelp:
    description: Displays help
    usage: /jahelp
  jainfo:
    description: Display information from a snitch
    usage: /jainfo
  jalist:
    description: Displays Juke List Information
    usage: /jalist
  jagroup:
    description: Display information from a group
    usage: /jagroup <group> <page>
    permission: jukealert.jagroup
  jaclear:
    description: Clear information from a snitch
    usage: /jaclear
  janame:
    description: Name a snitch
    usage: /janame
  jalookup:
    description: Look up a snitch by its coordinates
    usage: /jalookup <x> <y> <z> [world]
    permission: jukealert.jalookup
  jamute:
    description:  Adds or removes from a snitch notification ignore list.
    usage: /jamute <group> 
  jaconfig:
    description: Run-time configuration
    usage: /jaconfig <option> <value> 
    permission: jukealert.admin.jaconfig
permissions:
  jukealert.admin.jagroup:
    description: Use /jagroup even when not the owner
    default: false
  jukealert.admin.lookupany:
    description: Use /jalookup even when not the owner
    default: false
  jukealert.admin.jaconfig:
    description: Ability to use /jaconfig
    default: false
  jukealert.admin:
    description: Grants permission to JukeAlert admin commands.
    default: op
    children:
      jukealert.admin.jagroup: true
      jukealert.admin.lookupany: true
      jukealert.admin.jaconfig: true
  jukealert.jagroup:
    description: Ability to use /jagroup
    default: op
  jukealert.jalookup:
    description: Ability to use /jalookup
    default: true
